workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      node: v18.17.0
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Set up Expo
        script: |
          npm install -g @expo/cli@latest
          npx expo install --fix
      - name: Build Android APK
        script: |
          npx expo run:android --variant release
    artifacts:
      - android/app/build/outputs/**/*.apk
