workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      node: v18.17.0
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install -g @expo/cli@latest
      - name: Build Android APK
        script: |
          npx expo build:android --type apk --no-publish --clear-cache
    artifacts:
      - "*.apk"
    publishing:
      email:
        recipients:
          - build@bnbkit.com
        notify:
          success: true
          failure: false
